#ifndef ABSTRACT_SYNTAX_TREE_HEADER
#define ABSTRACT_SYNTAX_TREE_HEADER

#include "../../support/logging/Logger.h"
#include "../../support/type/ModuleDestructor.h"
#include <stdbool.h>
#include <stdlib.h>

/** Initialize module's internal state. */
ModuleDestructor initializeAbstractSyntaxTreeModule();

/**
 * This type definitions allows self-referencing types (e.g., an expression
 * that is made of another expressions, such as talking about you in 3rd
 * person, but without the madness).
 */

typedef enum DeclarationType DeclarationType;
typedef enum ExpressionType ExpressionType;
typedef enum FactorType FactorType;
typedef enum FundamentalType FundamentalType;
typedef enum StringPartType StringPartType;
typedef enum Unit Unit;

typedef struct Argument Argument;
typedef struct Arguments Arguments;
typedef struct Call Call;
typedef struct ConstantDeclaration ConstantDeclaration;
typedef struct Declaration Declaration;
typedef struct Declarations Declarations;
typedef struct Expression Expression;
typedef struct Factor Factor;
typedef struct Program Program;
typedef struct Quantity Quantity;
typedef struct Reference Reference;
typedef struct Simulation Simulation;
typedef struct StringLiteral StringLiteral;
typedef struct StringPart StringPart;
typedef struct StringParts StringParts;

/**
 * Node types for the Abstract Syntax Tree (AST). The enumerated values must
 * not collide with the token names generated by Bison, nor with the Flex
 * contexts (e.g., STRING or INTERPOLATION).
 */

enum DeclarationType {
	CONSTANT_DECLARATION
};

enum ExpressionType {
	ADDITION,
	ARITHMETIC_NEGATION,
	CONJUNCTION,
	DISJUNCTION,
	DIVISION,
	EQUALITY,
	FACTOR,
	GREATER_THAN,
	GREATER_THAN_OR_EQUAL_TO,
	INEQUALITY,
	LESS_THAN,
	LESS_THAN_OR_EQUAL_TO,
	LOGICAL_NEGATION,
	MULTIPLICATION,
	SUBTRACTION
};

enum FactorType {
	BOOLEAN_FACTOR,
	CALL_FACTOR,
	EXPRESSION_FACTOR,
	INTEGER_FACTOR,
	MEMBER_ACCESS_FACTOR,
	QUANTITY_FACTOR,
	REFERENCE_FACTOR,
	STRING_FACTOR
};

enum FundamentalType {
	BOOLEAN_FUNDAMENTAL_TYPE,
	DISTANCE_FUNDAMENTAL_TYPE,
	DURATION_FUNDAMENTAL_TYPE,
	INTEGER_FUNDAMENTAL_TYPE,
	SPEED_FUNDAMENTAL_TYPE,
	STRING_FUNDAMENTAL_TYPE
};

enum StringPartType {
	FRAGMENT_STRING_PART,
	INTERPOLATION_STRING_PART
};

enum Unit {
	HOURS_UNIT,
	KILOMETERS_PER_HOUR_UNIT,
	KILOMETERS_UNIT,
	METERS_PER_SECOND_UNIT,
	METERS_UNIT,
	MINUTES_UNIT,
	SECONDS_UNIT
};

struct Program {
	Simulation * simulation;
	Declarations * declarations;
};

struct Simulation {
	char * identifier;
	/** NULL if the simulation has no label. */
	Expression * label;
	Expression * duration;
};

/**
 * A list of declarations, in order of appearance.
 */
struct Declarations {
	Declaration * first;
	Declaration * last;
};

struct Declaration {
	union {
		ConstantDeclaration * constantDeclaration;
	};
	DeclarationType type;
	Declaration * next;
};

struct ConstantDeclaration {
	FundamentalType type;
	Reference * reference;
	Expression * expression;
};

struct Reference {
	char * identifier;
	/** NULL if the reference is not indexed. */
	Expression * index;
};

struct Expression {
	union {
		Factor * factor;
		Expression * expression;
		struct {
			Expression * leftExpression;
			Expression * rightExpression;
		};
	};
	ExpressionType type;
};

struct Factor {
	union {
		bool boolean;
		Call * call;
		Expression * expression;
		int integer;
		Quantity * quantity;
		Reference * reference;
		StringLiteral * stringLiteral;
		struct {
			Factor * factor;
			char * member;
		};
	};
	FactorType type;
};

struct Quantity {
	int value;
	Unit unit;
};

struct Call {
	char * identifier;
	Arguments * arguments;
};

/**
 * A list of arguments, in order of appearance.
 */
struct Arguments {
	Argument * first;
	Argument * last;
};

struct Argument {
	Expression * expression;
	Argument * next;
};

struct StringLiteral {
	StringParts * parts;
};

/**
 * A list of string parts, in order of appearance.
 */
struct StringParts {
	StringPart * first;
	StringPart * last;
};

struct StringPart {
	union {
		char * fragment;
		Expression * expression;
	};
	StringPartType type;
	StringPart * next;
};

/**
 * Node recursive super-duper-trambolik-destructors.
 */

void destroyArgument(Argument * argument);
void destroyArguments(Arguments * arguments);
void destroyCall(Call * call);
void destroyConstantDeclaration(ConstantDeclaration * constantDeclaration);
void destroyDeclaration(Declaration * declaration);
void destroyDeclarations(Declarations * declarations);
void destroyExpression(Expression * expression);
void destroyFactor(Factor * factor);
void destroyProgram(Program * program);
void destroyQuantity(Quantity * quantity);
void destroyReference(Reference * reference);
void destroySimulation(Simulation * simulation);
void destroyStringLiteral(StringLiteral * stringLiteral);
void destroyStringPart(StringPart * stringPart);
void destroyStringParts(StringParts * stringParts);

#endif
